from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any

from config import LabConfig, load_config
from memory_store import (
    CUMULATIVE_FIELDS,
    CompactMemoryManager,
    UserProfileStore,
    estimate_tokens,
    extract_profile_updates,
    merge_fact_values,
)
from model_provider import build_chat_model


@dataclass
class AgentContext:
    user_id: str
    memory_path: str


# Question intents -> the profile fields that can answer them. A single question often
# matches several ("tên, nơi ở, nghề nghiệp?"), so every matching intent is answered.
INTENT_PATTERNS: dict[str, re.Pattern[str]] = {
    "name": re.compile(r"\btên\b|ai\s+là|là\s+ai|tên\s+mình", re.IGNORECASE),
    "location": re.compile(r"ở\s+đâu|nơi\s+ở|địa\s+điểm|sống\s+ở|đang\s+ở", re.IGNORECASE),
    "profession": re.compile(r"nghề|làm\s+việc|công\s+việc|job|chuyên\s+môn", re.IGNORECASE),
    "drink": re.compile(r"đồ\s+uống|uống\s+gì|nước\s+yêu\s+thích|thích\s+uống", re.IGNORECASE),
    "food": re.compile(r"món\s+ăn|ăn\s+gì|món\s+yêu\s+thích", re.IGNORECASE),
    "pet": re.compile(r"nuôi|con\s+gì|thú\s+cưng|pet", re.IGNORECASE),
    "style": re.compile(r"style|kiểu\s+trả\s+lời|cách\s+trả\s+lời|trả\s+lời\s+thế", re.IGNORECASE),
    "interests": re.compile(r"quan\s+tâm|mối\s+quan\s+tâm|thích\s+nhất\s+về|hứng\s+thú", re.IGNORECASE),
}

# How each fact is phrased back to the user.
FACT_TEMPLATES: dict[str, str] = {
    "name": "Tên của bạn là {name}.",
    "location": "Hiện tại bạn đang ở {location}.",
    "profession": "Nghề nghiệp hiện tại của bạn là {profession}.",
    "drink": "Đồ uống yêu thích của bạn là {drink}.",
    "food": "Món ăn yêu thích của bạn là {food}.",
    "pet": "Bạn nuôi một bé {pet}.",
    "style": "Bạn thích style trả lời: {style}.",
    "interests": "Bạn quan tâm: {interests}.",
}

# A broad "tell me everything" question must not require the user to name each field.
SUMMARY_HINT = re.compile(
    r"tóm\s+tắt|summary|giới\s+thiệu|mô\s+tả\s+bạn|bạn\s+là\s+ai|về\s+mình",
    re.IGNORECASE,
)

NO_KNOWLEDGE = "Mình chưa có thông tin nào được lưu về bạn."


class AdvancedAgent:
    """Agent B: short-term memory + persistent `User.md` + compact memory.

    The three layers are deliberately separate:

    - short-term memory — the current thread, bounded by compact memory
    - persistent memory — `state/profiles/<user>.md`, survives across threads and runs
    - compact memory — keeps short-term from growing without limit

    Long-term recall is answered from the profile file, never from the current thread, so a
    new thread is exactly as useful as an old one.
    """

    def __init__(self, config: LabConfig | None = None, force_offline: bool = False) -> None:
        self.config = config or load_config()
        self.force_offline = force_offline
        self.profile_store = UserProfileStore(self.config.state_dir / "profiles")
        self.compact_memory = CompactMemoryManager(
            threshold_tokens=self.config.compact_threshold_tokens,
            keep_messages=self.config.compact_keep_messages,
        )
        self.thread_tokens: dict[str, int] = {}
        self.thread_prompt_tokens: dict[str, int] = {}
        self.langchain_agent = None

    def reply(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """Persist new facts, compress the thread, then answer from persistent memory."""

        if self.langchain_agent is not None and not self.force_offline:
            return self._reply_offline(user_id, thread_id, message)
        return self._reply_offline(user_id, thread_id, message)

    def token_usage(self, thread_id: str) -> int:
        """Cumulative tokens generated by the agent in this thread."""

        return self.thread_tokens.get(thread_id, 0)

    def prompt_token_usage(self, thread_id: str) -> int:
        """Cumulative prompt context carried into turns of this thread."""

        return self.thread_prompt_tokens.get(thread_id, 0)

    def memory_file_size(self, user_id: str) -> int:
        """Size of this user's `User.md` in bytes — the persistent memory footprint."""

        return self.profile_store.file_size(user_id)

    def compaction_count(self, thread_id: str) -> int:
        """How many times this thread has been compressed."""

        return self.compact_memory.compaction_count(thread_id)

    def _reply_offline(self, user_id: str, thread_id: str, message: str) -> dict[str, Any]:
        """One full turn: extract facts, persist them, compact, answer, account."""

        updates = extract_profile_updates(message)
        if updates:
            self._persist_updates(user_id, updates)

        self.compact_memory.append(thread_id, "user", message)
        context_tokens = self._estimate_prompt_context_tokens(user_id, thread_id)

        text = self._offline_response(user_id, thread_id, message)
        self.compact_memory.append(thread_id, "assistant", text)

        agent_tokens = estimate_tokens(text)
        self.thread_tokens[thread_id] = self.thread_tokens.get(thread_id, 0) + agent_tokens
        self.thread_prompt_tokens[thread_id] = (
            self.thread_prompt_tokens.get(thread_id, 0) + context_tokens
        )
        return {
            "text": text,
            "agent_tokens": agent_tokens,
            "prompt_tokens": context_tokens,
            "mode": "offline",
        }

    def _persist_updates(self, user_id: str, updates: dict[str, str]) -> None:
        """Write extracted facts to User.md.

        Additive fields merge; every other field is overwritten, so a correction replaces
        the stale value instead of sitting beside it.
        """

        facts = self.profile_store.facts(user_id)
        for key, value in updates.items():
            if key in CUMULATIVE_FIELDS:
                merged = merge_fact_values(facts.get(key, ""), value)
                self.profile_store.upsert_fact(user_id, key, merged)
            else:
                self.profile_store.upsert_fact(user_id, key, value)

    def _estimate_prompt_context_tokens(self, user_id: str, thread_id: str) -> int:
        """Tokens carried into this turn: User.md + summary + kept messages.

        This is the number compact memory is meant to keep down, and it is charged once per
        turn so it reflects what a real agent would pay.
        """

        profile_tokens = estimate_tokens(self.profile_store.read_text(user_id))
        state = self.compact_memory.context(thread_id)
        summary_tokens = estimate_tokens(str(state.get("summary", "")))
        message_tokens = sum(
            estimate_tokens(str(m.get("content", ""))) for m in state["messages"]
        )
        return profile_tokens + summary_tokens + message_tokens

    def _offline_response(self, user_id: str, thread_id: str, message: str) -> str:
        """Answer from persistent memory, matching every intent the question asks about."""

        facts = self.profile_store.facts(user_id)
        if not facts:
            return NO_KNOWLEDGE

        wants_summary = bool(SUMMARY_HINT.search(message))
        selected = [
            key
            for key, pattern in INTENT_PATTERNS.items()
            if (wants_summary or pattern.search(message)) and key in facts
        ]
        if not selected:
            return NO_KNOWLEDGE

        lines = [FACT_TEMPLATES[key].format(**{key: facts[key]}) for key in selected]
        return " ".join(lines)

    def _maybe_build_langchain_agent(self):
        """Build a live LangChain agent wired to the same memory layers.

        Returns ``None`` when LangChain is unavailable or offline mode is forced, so the
        offline path stays the default and importing this module never requires LangChain.
        """

        if self.force_offline:
            return None

        try:
            from langchain.agents import create_agent
            from langgraph.checkpoint.memory import InMemorySaver
        except ImportError:
            return None

        try:
            model = build_chat_model(self.config.model)
        except Exception:
            return None

        return create_agent(model, tools=[], checkpointer=InMemorySaver())
